import { Product } from '../src/types/store.js';

export const HERO_CAMPAIGN_IMAGE = '/src/assets/images/hero_campaign_aw26_1790917116291.jpg';
export const EDITORIAL_ATELIER_IMAGE = '/src/assets/images/editorial_atelier_lagos_1790917127723.jpg';

const IMG_NIA_TOP = '/src/assets/images/product_nia_draped_top_1790917140380.jpg';
const IMG_SADE_DRESS = '/src/assets/images/product_sade_column_dress_1790917152807.jpg';
const IMG_TOLU_TROUSER = '/src/assets/images/product_tolu_wide_trouser_1790917162690.jpg';
const IMG_DARA_BAG = '/src/assets/images/product_dara_structured_bag_1790917173757.jpg';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod_nia_draped_top',
    slug: 'nia-draped-top',
    name: 'Nia Draped Top',
    subtitle: 'Asymmetric cowl-neck blouse in raw bone silk',
    price: 165000,
    description:
      'Cut on a 45-degree bias from sandwashed mulberry silk, the Nia Draped Top falls across the collarbone with an asymmetric fold anchored by an internal grosgrain shoulder stay. Finished in our Victoria Island studio with hand-rolled hems and concealed side-seam mother-of-pearl closures.',
    category: 'Tops & Shirts',
    colour: 'Raw Bone',
    colour_hex: '#EAE4D8',
    images: [
      IMG_NIA_TOP,
      '/api/lookbook-plate/nia-draped-top/construction.svg',
      '/api/lookbook-plate/nia-draped-top/textile.svg',
    ],
    composition: '100% Sandwashed Mulberry Silk (22 Momme). Internal stay: 100% Organic Cotton grosgrain.',
    fit: 'Fluid bias fit through the torso; structured right shoulder. Model is 179cm and wears size S.',
    care: 'Specialist dry clean only. Steam lightly from the reverse side; do not press pleats flat.',
    shipping: 'Dispatched from Victoria Island, Lagos within 24–48 hours. Complimentary courier delivery across Lagos on orders above ₦250,000.',
    is_featured: true,
    is_new_arrival: true,
    editorial_aspect: '3:4',
    created_at: '2026-09-10T10:00:00.000Z',
    variants: [
      { id: 'var_nia_xs', product_id: 'prod_nia_draped_top', sku: 'AYE-AW26-NIA-XS', size: 'XS', colour: 'Raw Bone', inventory_quantity: 4 },
      { id: 'var_nia_s', product_id: 'prod_nia_draped_top', sku: 'AYE-AW26-NIA-S', size: 'S', colour: 'Raw Bone', inventory_quantity: 8 },
      { id: 'var_nia_m', product_id: 'prod_nia_draped_top', sku: 'AYE-AW26-NIA-M', size: 'M', colour: 'Raw Bone', inventory_quantity: 6 },
      { id: 'var_nia_l', product_id: 'prod_nia_draped_top', sku: 'AYE-AW26-NIA-L', size: 'L', colour: 'Raw Bone', inventory_quantity: 3 },
      { id: 'var_nia_xl', product_id: 'prod_nia_draped_top', sku: 'AYE-AW26-NIA-XL', size: 'XL', colour: 'Raw Bone', inventory_quantity: 0 },
    ],
  },
  {
    id: 'prod_sade_column_dress',
    slug: 'sade-column-dress',
    name: 'Sade Column Dress',
    subtitle: 'Ankle-grazing architectural bias dress in espresso crepe',
    price: 285000,
    description:
      'An elongated sleeveless column dress constructed from three spiralling panels of heavy matte viscose-silk crepe. A diagonal seam wraps from the left ribcage to the right ankle, allowing movement without breaking the vertical line.',
    category: 'Dresses',
    colour: 'Deep Espresso',
    colour_hex: '#281E18',
    images: [
      IMG_SADE_DRESS,
      '/api/lookbook-plate/sade-column-dress/construction.svg',
      '/api/lookbook-plate/sade-column-dress/textile.svg',
    ],
    composition: '72% FSC-Certified Viscose, 28% Mulberry Silk Heavy Crepe. Lining: 100% Cupro.',
    fit: 'Skims the body without clinging; ankle-grazing length (138cm from shoulder). Model is 180cm and wears size S.',
    care: 'Dry clean only. Store folded or hung from internal ribbon loops to preserve bias tension.',
    shipping: 'Dispatched from Victoria Island, Lagos within 24–48 hours. Express nationwide DHL available.',
    is_featured: true,
    is_new_arrival: true,
    editorial_aspect: '3:4',
    created_at: '2026-09-12T11:30:00.000Z',
    variants: [
      { id: 'var_sade_xs', product_id: 'prod_sade_column_dress', sku: 'AYE-AW26-SAD-XS', size: 'XS', colour: 'Deep Espresso', inventory_quantity: 3 },
      { id: 'var_sade_s', product_id: 'prod_sade_column_dress', sku: 'AYE-AW26-SAD-S', size: 'S', colour: 'Deep Espresso', inventory_quantity: 5 },
      { id: 'var_sade_m', product_id: 'prod_sade_column_dress', sku: 'AYE-AW26-SAD-M', size: 'M', colour: 'Deep Espresso', inventory_quantity: 7 },
      { id: 'var_sade_l', product_id: 'prod_sade_column_dress', sku: 'AYE-AW26-SAD-L', size: 'L', colour: 'Deep Espresso', inventory_quantity: 2 },
      { id: 'var_sade_xl', product_id: 'prod_sade_column_dress', sku: 'AYE-AW26-SAD-XL', size: 'XL', colour: 'Deep Espresso', inventory_quantity: 2 },
    ],
  },
  {
    id: 'prod_tolu_wide_trouser',
    slug: 'tolu-wide-leg-trouser',
    name: 'Tolu Wide-Leg Trouser',
    subtitle: 'Double-pleated tailored trouser in warm clay linen-wool',
    price: 195000,
    description:
      'High-waisted tailored trousers cut with deep inward-facing box pleats and an extended tab waistband. Woven from a breathable tropical wool and Belgian linen blend that holds a crisp press in coastal humidity.',
    category: 'Trousers & Skirts',
    colour: 'Warm Clay',
    colour_hex: '#B8A38E',
    images: [
      IMG_TOLU_TROUSER,
      '/api/lookbook-plate/tolu-wide-leg-trouser/construction.svg',
      '/api/lookbook-plate/tolu-wide-leg-trouser/textile.svg',
    ],
    composition: '55% Virgin Tropical Wool, 45% Unbleached Linen. Pocket bags: 100% Nigerian Combed Cotton.',
    fit: 'High rise; relaxed wide leg with 5cm blind hem allowance for bespoke lengthening.',
    care: 'Dry clean or cool hand wash with neutral wool detergent. Press with damp cloth.',
    shipping: 'Dispatched from Victoria Island, Lagos within 24–48 hours.',
    is_featured: true,
    is_new_arrival: true,
    editorial_aspect: '3:4',
    created_at: '2026-09-14T09:15:00.000Z',
    variants: [
      { id: 'var_tolu_xs', product_id: 'prod_tolu_wide_trouser', sku: 'AYE-AW26-TOL-XS', size: 'XS', colour: 'Warm Clay', inventory_quantity: 5 },
      { id: 'var_tolu_s', product_id: 'prod_tolu_wide_trouser', sku: 'AYE-AW26-TOL-S', size: 'S', colour: 'Warm Clay', inventory_quantity: 9 },
      { id: 'var_tolu_m', product_id: 'prod_tolu_wide_trouser', sku: 'AYE-AW26-TOL-M', size: 'M', colour: 'Warm Clay', inventory_quantity: 6 },
      { id: 'var_tolu_l', product_id: 'prod_tolu_wide_trouser', sku: 'AYE-AW26-TOL-L', size: 'L', colour: 'Warm Clay', inventory_quantity: 4 },
      { id: 'var_tolu_xl', product_id: 'prod_tolu_wide_trouser', sku: 'AYE-AW26-TOL-XL', size: 'XL', colour: 'Warm Clay', inventory_quantity: 3 },
    ],
  },
  {
    id: 'prod_dara_structured_bag',
    slug: 'dara-structured-bag',
    name: 'Dara Structured Bag',
    subtitle: 'Architectural trapezoid shoulder bag in roasted umber calfskin',
    price: 320000,
    description:
      'Hand-assembled over a molded vegetable-tanned leather core, the Dara Structured Bag pairs sharp gusseted geometry with a tubular shoulder strap anchored by solid brushed brass bar pins. Lined in unbleached cotton canvas with an internal card slip.',
    category: 'Leather Goods',
    colour: 'Roasted Umber',
    colour_hex: '#3E291E',
    images: [
      IMG_DARA_BAG,
      '/api/lookbook-plate/dara-structured-bag/construction.svg',
      '/api/lookbook-plate/dara-structured-bag/textile.svg',
    ],
    composition: '100% Full-Grain Vegetable-Tanned Calfskin. Hardware: Unlacquered Brushed Brass.',
    fit: 'Width: 28cm · Height: 17cm · Depth: 9.5cm · Handle Drop: 24cm.',
    care: 'Wipe with a dry soft cloth. Condition twice yearly with neutral leather balm; keep in provided unbleached cotton dust bag.',
    shipping: 'Ships in a rigid archival presentation box. Complimentary courier delivery throughout Lagos.',
    is_featured: true,
    is_new_arrival: true,
    editorial_aspect: '3:4',
    created_at: '2026-09-15T14:20:00.000Z',
    variants: [
      { id: 'var_dara_os', product_id: 'prod_dara_structured_bag', sku: 'AYE-AW26-DAR-OS', size: 'ONE SIZE', colour: 'Roasted Umber', inventory_quantity: 6 },
    ],
  },
  {
    id: 'prod_eko_poplin_shirt',
    slug: 'eko-poplin-shirt',
    name: 'Eko Poplin Shirt',
    subtitle: 'Oversized architectural shirt with gusseted back yoke',
    price: 140000,
    description:
      'A study in crisp volume, the Eko Shirt reworks classic menswear shirting with a dropped shoulder, elongated mitered cuffs, and a cantilevered back pleat that creates an architectural arc when viewed in profile. Fastened with carved horn buttons.',
    category: 'Tops & Shirts',
    colour: 'Chalk Ivory',
    colour_hex: '#F3EFE6',
    images: [
      '/api/lookbook-photo/eko-poplin-shirt.svg',
      '/api/lookbook-plate/eko-poplin-shirt/construction.svg',
      '/api/lookbook-plate/eko-poplin-shirt/textile.svg',
    ],
    composition: '100% Long-Staple Organic Cotton Poplin (135 GSM). Buttons: Natural ethically sourced Nigerian Zebu horn.',
    fit: 'Generous, architectural cut. Take your normal size for an oversized silhouette or size down for a closer shoulder.',
    care: 'Machine wash cold on gentle cycle or hand wash. Line dry in shade; steam while slightly damp.',
    shipping: 'Dispatched from Victoria Island, Lagos within 24–48 hours.',
    is_featured: false,
    is_new_arrival: true,
    editorial_aspect: '3:4',
    created_at: '2026-09-16T08:00:00.000Z',
    variants: [
      { id: 'var_eko_xs', product_id: 'prod_eko_poplin_shirt', sku: 'AYE-AW26-EKO-XS', size: 'XS', colour: 'Chalk Ivory', inventory_quantity: 6 },
      { id: 'var_eko_s', product_id: 'prod_eko_poplin_shirt', sku: 'AYE-AW26-EKO-S', size: 'S', colour: 'Chalk Ivory', inventory_quantity: 10 },
      { id: 'var_eko_m', product_id: 'prod_eko_poplin_shirt', sku: 'AYE-AW26-EKO-M', size: 'M', colour: 'Chalk Ivory', inventory_quantity: 8 },
      { id: 'var_eko_l', product_id: 'prod_eko_poplin_shirt', sku: 'AYE-AW26-EKO-L', size: 'L', colour: 'Chalk Ivory', inventory_quantity: 5 },
      { id: 'var_eko_xl', product_id: 'prod_eko_poplin_shirt', sku: 'AYE-AW26-EKO-XL', size: 'XL', colour: 'Chalk Ivory', inventory_quantity: 3 },
    ],
  },
  {
    id: 'prod_imani_bias_skirt',
    slug: 'imani-bias-skirt',
    name: 'Imani Bias Skirt',
    subtitle: 'Mid-calf panelled bias skirt in dark umber satin',
    price: 175000,
    description:
      'Constructed with French seams set at opposing angles, the Imani Bias Skirt balances a matte interior against a low-lustre hammered satin face. Sits cleanly at the natural waist with a concealed grosgrain facing rather than a bulky waistband.',
    category: 'Trousers & Skirts',
    colour: 'Dark Umber',
    colour_hex: '#423127',
    images: [
      '/api/lookbook-photo/imani-bias-skirt.svg',
      '/api/lookbook-plate/imani-bias-skirt/construction.svg',
      '/api/lookbook-plate/imani-bias-skirt/textile.svg',
    ],
    composition: '100% Heavyweight Hammered Silk Satin (28 Momme).',
    fit: 'True to size at the waist; fluid through the hip. Length: 88cm.',
    care: 'Specialist dry clean only.',
    shipping: 'Dispatched from Victoria Island, Lagos within 24–48 hours.',
    is_featured: false,
    is_new_arrival: true,
    editorial_aspect: '3:4',
    created_at: '2026-09-17T12:00:00.000Z',
    variants: [
      { id: 'var_imani_xs', product_id: 'prod_imani_bias_skirt', sku: 'AYE-AW26-IMA-XS', size: 'XS', colour: 'Dark Umber', inventory_quantity: 3 },
      { id: 'var_imani_s', product_id: 'prod_imani_bias_skirt', sku: 'AYE-AW26-IMA-S', size: 'S', colour: 'Dark Umber', inventory_quantity: 7 },
      { id: 'var_imani_m', product_id: 'prod_imani_bias_skirt', sku: 'AYE-AW26-IMA-M', size: 'M', colour: 'Dark Umber', inventory_quantity: 5 },
      { id: 'var_imani_l', product_id: 'prod_imani_bias_skirt', sku: 'AYE-AW26-IMA-L', size: 'L', colour: 'Dark Umber', inventory_quantity: 4 },
      { id: 'var_imani_xl', product_id: 'prod_imani_bias_skirt', sku: 'AYE-AW26-IMA-XL', size: 'XL', colour: 'Dark Umber', inventory_quantity: 1 },
    ],
  },
  {
    id: 'prod_kemi_wrap_dress',
    slug: 'kemi-wrap-dress',
    name: 'Kemi Wrap Dress',
    subtitle: 'Sculpted kimono-sleeve wrap dress in ochre earth linen',
    price: 245000,
    description:
      'Drawing subtly from the geometry of traditional Yoruba iro wrapping without literal ornament, the Kemi Dress secures via an internal button tab and an external wide self-tie belt that tunnels through the back waist.',
    category: 'Dresses',
    colour: 'Ochre Earth',
    colour_hex: '#8C5B3E',
    images: [
      '/api/lookbook-photo/kemi-wrap-dress.svg',
      '/api/lookbook-plate/kemi-wrap-dress/construction.svg',
      '/api/lookbook-plate/kemi-wrap-dress/textile.svg',
    ],
    composition: '100% Heavyweight Washed Flax Linen (240 GSM).',
    fit: 'Adjustable waist tension via internal two-position corozo button and external sash.',
    care: 'Cool gentle wash or dry clean. Iron on reverse while damp.',
    shipping: 'Dispatched from Victoria Island, Lagos within 24–48 hours.',
    is_featured: true,
    is_new_arrival: false,
    editorial_aspect: '3:4',
    created_at: '2026-09-18T15:00:00.000Z',
    variants: [
      { id: 'var_kemi_xs', product_id: 'prod_kemi_wrap_dress', sku: 'AYE-AW26-KEM-XS', size: 'XS', colour: 'Ochre Earth', inventory_quantity: 4 },
      { id: 'var_kemi_s', product_id: 'prod_kemi_wrap_dress', sku: 'AYE-AW26-KEM-S', size: 'S', colour: 'Ochre Earth', inventory_quantity: 6 },
      { id: 'var_kemi_m', product_id: 'prod_kemi_wrap_dress', sku: 'AYE-AW26-KEM-M', size: 'M', colour: 'Ochre Earth', inventory_quantity: 5 },
      { id: 'var_kemi_l', product_id: 'prod_kemi_wrap_dress', sku: 'AYE-AW26-KEM-L', size: 'L', colour: 'Ochre Earth', inventory_quantity: 3 },
      { id: 'var_kemi_xl', product_id: 'prod_kemi_wrap_dress', sku: 'AYE-AW26-KEM-XL', size: 'XL', colour: 'Ochre Earth', inventory_quantity: 2 },
    ],
  },
  {
    id: 'prod_zainab_sculpted_blazer',
    slug: 'zainab-sculpted-blazer',
    name: 'Zainab Sculpted Blazer',
    subtitle: 'Collarless single-breasted jacket with darted waist',
    price: 340000,
    description:
      'Tailored in Lagos with soft horsehair canvas through the chest, the Zainab Blazer omits traditional lapels in favour of a clean V-neck line and contoured waist darts that flare gently over the hip.',
    category: 'Outerwear',
    colour: 'Charcoal Stone',
    colour_hex: '#2F2D2A',
    images: [
      '/api/lookbook-photo/zainab-sculpted-blazer.svg',
      '/api/lookbook-plate/zainab-sculpted-blazer/construction.svg',
      '/api/lookbook-plate/zainab-sculpted-blazer/textile.svg',
    ],
    composition: '100% Virgin Wool Cavalry Twill. Lining: 100% Bemberg Cupro.',
    fit: 'Structured shoulder with a contoured waist. Take your usual tailoring size.',
    care: 'Specialist dry clean only. Brush gently with a soft garment brush after wear.',
    shipping: 'Ships on a contoured beechwood hanger inside a breathable cotton garment cover.',
    is_featured: false,
    is_new_arrival: true,
    editorial_aspect: '3:4',
    created_at: '2026-09-19T10:30:00.000Z',
    variants: [
      { id: 'var_zainab_xs', product_id: 'prod_zainab_sculpted_blazer', sku: 'AYE-AW26-ZAI-XS', size: 'XS', colour: 'Charcoal Stone', inventory_quantity: 2 },
      { id: 'var_zainab_s', product_id: 'prod_zainab_sculpted_blazer', sku: 'AYE-AW26-ZAI-S', size: 'S', colour: 'Charcoal Stone', inventory_quantity: 5 },
      { id: 'var_zainab_m', product_id: 'prod_zainab_sculpted_blazer', sku: 'AYE-AW26-ZAI-M', size: 'M', colour: 'Charcoal Stone', inventory_quantity: 4 },
      { id: 'var_zainab_l', product_id: 'prod_zainab_sculpted_blazer', sku: 'AYE-AW26-ZAI-L', size: 'L', colour: 'Charcoal Stone', inventory_quantity: 3 },
      { id: 'var_zainab_xl', product_id: 'prod_zainab_sculpted_blazer', sku: 'AYE-AW26-ZAI-XL', size: 'XL', colour: 'Charcoal Stone', inventory_quantity: 1 },
    ],
  },
  {
    id: 'prod_amina_loomed_overshirt',
    slug: 'amina-loomed-overshirt',
    name: 'Amina Loomed Overshirt',
    subtitle: 'Hand-loomed Iseyin Aso-Oke cotton jacket with concealed placket',
    price: 230000,
    description:
      'Woven in 14cm narrow strips by master weavers in Iseyin, Oyo State, and joined with open faggoting seams in our Lagos studio. Unbleached indigenous cotton gives the surface a dry, architectural hand that softens over decades.',
    category: 'Outerwear',
    colour: 'Unbleached Ecru',
    colour_hex: '#DFD7C8',
    images: [
      '/api/lookbook-photo/amina-loomed-overshirt.svg',
      '/api/lookbook-plate/amina-loomed-overshirt/construction.svg',
      '/api/lookbook-plate/amina-loomed-overshirt/textile.svg',
    ],
    composition: '100% Hand-Loomed Nigerian Strip-Weave Cotton (Aso-Oke). Unlined with bound internal seams.',
    fit: 'Boxy, cropped just below the hip bone. Designed to layer over dresses or high-waisted trousers.',
    care: 'Dry clean or cold hand wash separately. Do not wring; dry flat.',
    shipping: 'Dispatched from Victoria Island, Lagos within 24–48 hours.',
    is_featured: true,
    is_new_arrival: true,
    editorial_aspect: '3:4',
    created_at: '2026-09-20T16:45:00.000Z',
    variants: [
      { id: 'var_amina_xs', product_id: 'prod_amina_loomed_overshirt', sku: 'AYE-AW26-AMI-XS', size: 'XS', colour: 'Unbleached Ecru', inventory_quantity: 3 },
      { id: 'var_amina_s', product_id: 'prod_amina_loomed_overshirt', sku: 'AYE-AW26-AMI-S', size: 'S', colour: 'Unbleached Ecru', inventory_quantity: 4 },
      { id: 'var_amina_m', product_id: 'prod_amina_loomed_overshirt', sku: 'AYE-AW26-AMI-M', size: 'M', colour: 'Unbleached Ecru', inventory_quantity: 5 },
      { id: 'var_amina_l', product_id: 'prod_amina_loomed_overshirt', sku: 'AYE-AW26-AMI-L', size: 'L', colour: 'Unbleached Ecru', inventory_quantity: 2 },
      { id: 'var_amina_xl', product_id: 'prod_amina_loomed_overshirt', sku: 'AYE-AW26-AMI-XL', size: 'XL', colour: 'Unbleached Ecru', inventory_quantity: 0 },
    ],
  },
  {
    id: 'prod_yemi_pleated_tunic',
    slug: 'yemi-pleated-tunic',
    name: 'Yemi Pleated Tunic',
    subtitle: 'Elongated split-hem tunic with knife-pleated back panel',
    price: 180000,
    description:
      'Clean and minimal from the front, the Yemi Tunic opens into a fan of pressed knife pleats set into the mid-shoulder blade yolk. High side splits allow effortless movement over tailored trousers.',
    category: 'Tops & Shirts',
    colour: 'Smoked Papyrus',
    colour_hex: '#CEC4B4',
    images: [
      '/api/lookbook-photo/yemi-pleated-tunic.svg',
      '/api/lookbook-plate/yemi-pleated-tunic/construction.svg',
      '/api/lookbook-plate/yemi-pleated-tunic/textile.svg',
    ],
    composition: '68% Tencel Lyocell, 32% Linen Suiting.',
    fit: 'Relaxed straight cut with high side vents.',
    care: 'Dry clean recommended to maintain sharp knife pleat memory.',
    shipping: 'Dispatched from Victoria Island, Lagos within 24–48 hours.',
    is_featured: false,
    is_new_arrival: false,
    editorial_aspect: '3:4',
    created_at: '2026-09-21T09:00:00.000Z',
    variants: [
      { id: 'var_yemi_xs', product_id: 'prod_yemi_pleated_tunic', sku: 'AYE-AW26-YEM-XS', size: 'XS', colour: 'Smoked Papyrus', inventory_quantity: 4 },
      { id: 'var_yemi_s', product_id: 'prod_yemi_pleated_tunic', sku: 'AYE-AW26-YEM-S', size: 'S', colour: 'Smoked Papyrus', inventory_quantity: 6 },
      { id: 'var_yemi_m', product_id: 'prod_yemi_pleated_tunic', sku: 'AYE-AW26-YEM-M', size: 'M', colour: 'Smoked Papyrus', inventory_quantity: 6 },
      { id: 'var_yemi_l', product_id: 'prod_yemi_pleated_tunic', sku: 'AYE-AW26-YEM-L', size: 'L', colour: 'Smoked Papyrus', inventory_quantity: 3 },
      { id: 'var_yemi_xl', product_id: 'prod_yemi_pleated_tunic', sku: 'AYE-AW26-YEM-XL', size: 'XL', colour: 'Smoked Papyrus', inventory_quantity: 2 },
    ],
  },
  {
    id: 'prod_bisi_architectural_trench',
    slug: 'bisi-architectural-trench',
    name: 'Bisi Architectural Trench',
    subtitle: 'Unlined raglan duster coat in water-repellent cotton gabardine',
    price: 410000,
    description:
      'Engineered for Lagos rainy-season transitions and international travel, the Bisi Trench removes standard epaulettes and storm flaps in favour of a sweeping two-piece raglan sleeve, deep welt pockets, and French-bound interior seams.',
    category: 'Outerwear',
    colour: 'Warm Putty',
    colour_hex: '#C6BCA9',
    images: [
      '/api/lookbook-photo/bisi-architectural-trench.svg',
      '/api/lookbook-plate/bisi-architectural-trench/construction.svg',
      '/api/lookbook-plate/bisi-architectural-trench/textile.svg',
    ],
    composition: '100% High-Density Combed Cotton Gabardine with PFC-free water-repellent finish.',
    fit: 'Generous sweeping silhouette; self-fabric belt included.',
    care: 'Specialist dry clean only.',
    shipping: 'Complimentary express courier delivery included.',
    is_featured: false,
    is_new_arrival: false,
    editorial_aspect: '3:4',
    created_at: '2026-09-22T11:10:00.000Z',
    variants: [
      { id: 'var_bisi_xs', product_id: 'prod_bisi_architectural_trench', sku: 'AYE-AW26-BIS-XS', size: 'XS', colour: 'Warm Putty', inventory_quantity: 2 },
      { id: 'var_bisi_s', product_id: 'prod_bisi_architectural_trench', sku: 'AYE-AW26-BIS-S', size: 'S', colour: 'Warm Putty', inventory_quantity: 4 },
      { id: 'var_bisi_m', product_id: 'prod_bisi_architectural_trench', sku: 'AYE-AW26-BIS-M', size: 'M', colour: 'Warm Putty', inventory_quantity: 3 },
      { id: 'var_bisi_l', product_id: 'prod_bisi_architectural_trench', sku: 'AYE-AW26-BIS-L', size: 'L', colour: 'Warm Putty', inventory_quantity: 2 },
      { id: 'var_bisi_xl', product_id: 'prod_bisi_architectural_trench', sku: 'AYE-AW26-BIS-XL', size: 'XL', colour: 'Warm Putty', inventory_quantity: 1 },
    ],
  },
  {
    id: 'prod_amara_asymmetric_slip',
    slug: 'amara-asymmetric-slip',
    name: 'Amara Asymmetric Slip',
    subtitle: 'Double-layered silk georgette midi dress with raw-edge godet',
    price: 260000,
    description:
      'Cut in two suspended layers of matte silk georgette in burnt sienna, the Amara Slip features fine rouleau straps that cross at a low architectural back and an asymmetric hem weighted with a delicate twin-needle stitch.',
    category: 'Dresses',
    colour: 'Burnt Sienna',
    colour_hex: '#7C4D36',
    images: [
      '/api/lookbook-photo/amara-asymmetric-slip.svg',
      '/api/lookbook-plate/amara-asymmetric-slip/construction.svg',
      '/api/lookbook-plate/amara-asymmetric-slip/textile.svg',
    ],
    composition: '100% Silk Crêpe Georgette (double layer).',
    fit: 'Bias cut; moulds gently to the body. Adjustable back strap slider.',
    care: 'Specialist dry clean only.',
    shipping: 'Dispatched from Victoria Island, Lagos within 24–48 hours.',
    is_featured: false,
    is_new_arrival: true,
    editorial_aspect: '3:4',
    created_at: '2026-09-23T13:20:00.000Z',
    variants: [
      { id: 'var_amara_xs', product_id: 'prod_amara_asymmetric_slip', sku: 'AYE-AW26-AMA-XS', size: 'XS', colour: 'Burnt Sienna', inventory_quantity: 3 },
      { id: 'var_amara_s', product_id: 'prod_amara_asymmetric_slip', sku: 'AYE-AW26-AMA-S', size: 'S', colour: 'Burnt Sienna', inventory_quantity: 5 },
      { id: 'var_amara_m', product_id: 'prod_amara_asymmetric_slip', sku: 'AYE-AW26-AMA-M', size: 'M', colour: 'Burnt Sienna', inventory_quantity: 4 },
      { id: 'var_amara_l', product_id: 'prod_amara_asymmetric_slip', sku: 'AYE-AW26-AMA-L', size: 'L', colour: 'Burnt Sienna', inventory_quantity: 3 },
      { id: 'var_amara_xl', product_id: 'prod_amara_asymmetric_slip', sku: 'AYE-AW26-AMA-XL', size: 'XL', colour: 'Burnt Sienna', inventory_quantity: 1 },
    ],
  },
  {
    id: 'prod_oluwa_tailored_culotte',
    slug: 'oluwa-tailored-culotte',
    name: 'Oluwa Tailored Culotte',
    subtitle: 'Below-the-knee wide gaucho trouser in near-black virgin wool',
    price: 185000,
    description:
      'Designed with the volume of a midi skirt and the precision of bespoke menswear trousers. Features a clean hook-and-bar waistband, slanted side pockets, and a deep front overlap pleat.',
    category: 'Trousers & Skirts',
    colour: 'Near-Black',
    colour_hex: '#191817',
    images: [
      '/api/lookbook-photo/oluwa-tailored-culotte.svg',
      '/api/lookbook-plate/oluwa-tailored-culotte/construction.svg',
      '/api/lookbook-plate/oluwa-tailored-culotte/textile.svg',
    ],
    composition: '100% High-Twist Virgin Wool (210 GSM).',
    fit: 'Mid-high waist; cropped mid-calf length.',
    care: 'Dry clean only.',
    shipping: 'Dispatched from Victoria Island, Lagos within 24–48 hours.',
    is_featured: false,
    is_new_arrival: false,
    editorial_aspect: '3:4',
    created_at: '2026-09-24T10:00:00.000Z',
    variants: [
      { id: 'var_oluwa_xs', product_id: 'prod_oluwa_tailored_culotte', sku: 'AYE-AW26-OLU-XS', size: 'XS', colour: 'Near-Black', inventory_quantity: 4 },
      { id: 'var_oluwa_s', product_id: 'prod_oluwa_tailored_culotte', sku: 'AYE-AW26-OLU-S', size: 'S', colour: 'Near-Black', inventory_quantity: 7 },
      { id: 'var_oluwa_m', product_id: 'prod_oluwa_tailored_culotte', sku: 'AYE-AW26-OLU-M', size: 'M', colour: 'Near-Black', inventory_quantity: 6 },
      { id: 'var_oluwa_l', product_id: 'prod_oluwa_tailored_culotte', sku: 'AYE-AW26-OLU-L', size: 'L', colour: 'Near-Black', inventory_quantity: 4 },
      { id: 'var_oluwa_xl', product_id: 'prod_oluwa_tailored_culotte', sku: 'AYE-AW26-OLU-XL', size: 'XL', colour: 'Near-Black', inventory_quantity: 2 },
    ],
  },
  {
    id: 'prod_femi_knot_crossbody',
    slug: 'femi-knot-crossbody',
    name: 'Femi Knot Crossbody',
    subtitle: 'Soft-folded pouch bag in blackened espresso grained calfskin',
    price: 275000,
    description:
      'Crafted from two origami-folded panels of supple grained leather, the Femi Crossbody adjusts via a hand-knotted leather cord and conceals a magnetic brass frame closure along the top ridge.',
    category: 'Leather Goods',
    colour: 'Blackened Espresso',
    colour_hex: '#1E1815',
    images: [
      '/api/lookbook-photo/femi-knot-crossbody.svg',
      '/api/lookbook-plate/femi-knot-crossbody/construction.svg',
      '/api/lookbook-plate/femi-knot-crossbody/textile.svg',
    ],
    composition: '100% Drum-Dyed Grained Calfskin. Suede-backed interior.',
    fit: 'Width: 24cm · Height: 19cm · Depth: 8cm · Adjustable strap drop: 32cm–56cm.',
    care: 'Keep dry and store stuffed with acid-free tissue inside its cotton dust bag.',
    shipping: 'Complimentary courier delivery throughout Lagos.',
    is_featured: false,
    is_new_arrival: true,
    editorial_aspect: '3:4',
    created_at: '2026-09-25T15:30:00.000Z',
    variants: [
      { id: 'var_femi_os', product_id: 'prod_femi_knot_crossbody', sku: 'AYE-AW26-FEM-OS', size: 'ONE SIZE', colour: 'Blackened Espresso', inventory_quantity: 5 },
    ],
  },
];
